version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
